[package]
name = "rust-kr"
version = "0.1.0"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]

[dependencies]
iron = "0.4"
router = "0.2"
staticfile = "0.3"
handlebars-iron = { version = "0.18", features = ["serde_type"] }
pulldown-cmark = "0.0.8"
